### ISSUE TITLE
Reactive library

### ISSUE THREAD

**Issue by LeiYangGH** [vain0/VainZero.WpfReportPrinting#1]
Hi VainZero,

I'm impressed by this project and when I am looking for a library to print table in WPF.
But when I downloaded the Reactive library overwhelmed me. I often use MVVM light toolkit.
So I tried to remove all Reactive library and minimized this demo.
And then uploaded it here:
https://github.com/LeiYangGH/ElectricWarehouse/tree/master/WpfReportPrinting
Can you consider make a branch like this?

Regards,
Yang Lei

**Comment by vain0** [comment]
Hello.
I agree with your suggestion that the Demo project should provide samples without reactive libraries.

I looked at your edition. I don't think removing bindings and abstractions (such as Printer, IPaginatable) helps developpers because WPF developpers are likely familiar with bindings and they finally need abstractions in their actual code base.

I want to modify that project to use one of other frameworks (MVVM light toolkit or maybe Prism?) before long.

Thank you,
vain0

**Comment by LeiYangGH** [comment]
thanks!

**Comment by vain0** [comment]
Note that this repository is now deprecated and I has worked on [DotNetKit.Wpf.Printing](https://github.com/DotNetKit/DotNetKit.Wpf.Printing) (because VainZero namespace seems inappropriate for open source libraries).

The sample project in that repo is improved by your advice. Thanks.
